admin_learn/urls.py
from django.contrib import admin
from django.urls import path
from firstapp import views  # Импортируем views из приложения firstapp

urlpatterns = [
    path('admin/', admin.site.urls),  # Путь для админки
    path('', views.index, name='index'),  # Путь для главной страницы
    path('courses/', views.course_list, name='course_list'),  # Путь для списка курсов
    path('teachers/', views.teacher_list, name='teacher_list'),  # Путь для списка преподавателей
    path('course/<int:id>/', views.course_detail, name='course_detail'),  # Путь для подробностей курса
    path('teacher/<int:id>/', views.teacher_detail, name='teacher_detail'),  # Путь для подробностей преподавателя
    path('course_list_view/', views.CourseListView.as_view(), name='course_list_view'),  # Путь для представления на основе класса
]

firstapp/urls.py
from django.contrib import admin
from django.urls import path
from firstapp import views  # Импортируем views из приложения firstapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('courses/', views.course_list, name='course_list'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('course/<int:id>/', views.course_detail, name='course_detail'),
    path('teacher/<int:id>/', views.teacher_detail, name='teacher_detail'),
    path('course_list_view/', views.CourseListView.as_view(), name='course_list_view'),
]

firstapp/models.py
from django.db import models
from django.urls import reverse


class Faculty(models.Model):
    name = models.CharField(max_length=200, help_text="Введите наименование факультета")

    def __str__(self):
        return self.name


class Course(models.Model):
    title = models.CharField(max_length=200)
    teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Введите описание учебного курса")
    faculty = models.ManyToManyField(Faculty, help_text="Выберите факультет")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('firstapp:course_detail', args=[str(self.id)])

    def display_faculty(self):
        return ', '.join([faculty.name for faculty in self.faculty.all()[:3]])  # возвращает строку

    display_faculty.short_description = 'Faculty'


class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('firstapp:teacher_detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

firstapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import Course, Teacher, Faculty


def index(request):
    num_course = Course.objects.count()
    num_teacher = Teacher.objects.count()
    num_faculty = Faculty.objects.count()

    return render(
        request,
        'index.html',
        context={
            'num_course': num_course,
            'num_teacher': num_teacher,
            'num_faculty': num_faculty
        }
    )


def course_list(request):
    return render(
        request,
        'course_list.html',
        context={'course_list': Course.objects.all()}
    )


def teacher_list(request):
    return render(
        request,
        'teacher_list.html',
        context={'teacher_list': Teacher.objects.all()}
    )


def course_detail(request, id):
    course = get_object_or_404(Course, pk=id)
    return render(request, 'course_detail.html', {'course': course})


def teacher_detail(request, id):
    teacher = get_object_or_404(Teacher, pk=id)
    return render(request, 'teacher_detail.html', {'teacher': teacher})


class CourseListView(ListView):
    model = Course
    template_name = "firstapp/course_list.html"

    

firstapp/templates/base_generic.html
<!DOCTYPE html>
<head>
    <meta charset="windows-1251">
    <title>Сайт колледжа</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style> .sidebar-nav { margin-top: 20px; padding: 0; list-style: none; } </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <li><a href="/firstapp/course">Все курсы</a></li>
                <li><a href="/firstapp/teacher">Преподаватели</a></li>
            </ul>
        </div>
        <div class="col-sm-10">
            <h1>Главная страница</h1>
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

firstapp/templates/course_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Сайт колледжа</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style> .sidebar-nav { margin-top: 20px; padding: 0; list-style: none; } </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <li><a href="/firstapp/course">Все курсы</a></li>
                <li><a href="/firstapp/teacher">Преподаватели</a></li>
            </ul>
        </div>
        <div class="col-sm-10">
            <h1>Название курса: {{ course.title }}</h1>
            <p><strong>Преподаватель:</strong> <a href="">{{ course.teacher }}</a></p>
            <p><strong>Описание:</strong> {{ course.summary }}</p>
            <p><strong>Факультет:</strong>
                {% for faculty in course.faculty.all %}
                    {{ faculty }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <div style="margin-left:20px;margin-top:20px">
            </div>
        </div>
    </div>
</div>
</body>
</html>

firstapp/templates/course_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="windows-1251">
    <title>Сайт колледжа</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style> .sidebar-nav { margin-top: 20px; padding: 0; list-style: none; } </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <li><a href="#">Все курсы</a></li>
                <li><a href="#">Преподаватели</a></li>
            </ul>
        </div>
        <div class="col-sm-10">
            <h1>Список курсов</h1>
            {% if course_list %}
            <ul>
                {% for course in course_list %}
                <li>
                    <a href="{{ course.get_absolute_url }}">{{ course.title }}</a>
                    ({{course.teacher}})
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>Курсы не найдены.</p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

firstapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="windows-1251">
    <title>Сайт колледжа</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style> .sidebar-nav { margin-top: 20px; padding: 0; list-style: none; } </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <li><a href="/firstapp/course">Все курсы</a></li>
                <li><a href="/firstapp/teacher">Преподаватели</a></li>
            </ul>
        </div>
        <div class="col-sm-10 ">
            <h1>Главная страница колледжа</h1>
            <p>Добро пожаловать на наш веб-сайт!!</p>
            <h2>Наши продукты</h2>
            <p>Колледжи:</p>
            <ul>
                <li><strong>Курсы:</strong> {{ num_course }}</li>
                <li><strong>Преподаватели:</strong> {{ num_teacher }}</li>
                <li><strong>Факультеты:</strong> {{ num_faculty }}</li>
            </ul>
        </div>
    </div>
</div>
</body>
</html>

firstapp/templates/teacher_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Сайт колледжа</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style> .sidebar-nav { margin-top: 20px; padding: 0; list-style: none; } </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <li><a href="/firstapp/course">Все курсы</a></li>
                <li><a href="/firstapp/teacher">Преподаватели</a></li>
            </ul>
        </div>
        <div class="col-sm-10 ">
            <h1>Преподаватель: {{ teacher.first_name }} {{ teacher.last_name }}</h1>
            <p><strong>Дата рождения:</strong> {{ teacher.date_of_birth }}</p>
            <p><strong>Преподаваемые курсы:</strong></p>
            <ul>
                {% for course in teacher.course_set.all %}
                <li><a href="{{ course.get_absolute_url }}">{{ course.title }}</a></li>
                {% empty %}
                <li>Нет доступных курсов</li>
                {% endfor %}
            </ul>
            <div style="margin-left:20px;margin-top:20px">
            </div>
        </div>
    </div>
</div>
</body>
</html>

firstapp/templates/teacher_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Сайт колледжа - Преподаватели</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style> .sidebar-nav { margin-top: 20px; padding: 0; list-style: none; } </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <li><a href="/firstapp/course">Все курсы</a></li>
                <li><a href="/firstapp/teacher">Преподаватели</a></li>
            </ul>
        </div>
        <div class="col-sm-10">
            <h1>Список преподавателей</h1>
            {% if teacher_list %}
            <ul>
                {% for teacher in teacher_list %}
                <li>
                    <a href="{{ teacher.get_absolute_url }}">{{ teacher.first_name }} {{ teacher.last_name }}</a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>Преподаватели не найдены.</p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>